osx_image: xcode9.2
language: objective-c

before_install:
    - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
    - export LANG=en_US.UTF-8

script: xcodebuild clean test -project InterfaCSS.xcodeproj -scheme UnitTests -destination 'platform=iOS Simulator,name=iPhone 7' | xcpretty -c && exit ${PIPESTATUS[0]}
