osx_image: xcode10.1
language: objective-c

before_install:
    - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
    - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
    - export LANG=en_US.UTF-8
    - pod install

script: xcodebuild clean test -workspace InterfaCSS.xcworkspace -scheme CoreTests -destination 'platform=iOS Simulator,name=iPhone X' | xcpretty -c && exit ${PIPESTATUS[0]}
